/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ProductSitemapDotxmlRouteImport } from './routes/product-sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminDiscountsRouteImport } from './routes/_authenticated/admin/discounts'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTorobRouteImport } from './routes/_authenticated/admin/torob'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiTorobHealthRouteImport } from './routes/api/torob/health'
import { Route as ApiTorobProductsRouteImport } from './routes/api/torob/products'
import { Route as ApiPaymentZibalCallbackRouteImport } from './routes/api/payment/zibal/callback'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img.$'
import { Route as ApiPublicModelSplatRouteImport } from './routes/api/public/model.$'
import { Route as ApiTorobV1OrdersRouteImport } from './routes/api/torob/v1/orders'
import { Route as ApiTorobWebhooksProcessRouteImport } from './routes/api/torob/webhooks/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSitemapDotxmlRoute = ProductSitemapDotxmlRouteImport.update({
  id: '/product-sitemap.xml',
  path: '/product-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDiscountsRoute =
  AuthenticatedAdminDiscountsRouteImport.update({
    id: '/discounts',
    path: '/discounts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTorobRoute = AuthenticatedAdminTorobRouteImport.update({
  id: '/torob',
  path: '/torob',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorobHealthRoute = ApiTorobHealthRouteImport.update({
  id: '/api/torob/health',
  path: '/api/torob/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorobProductsRoute = ApiTorobProductsRouteImport.update({
  id: '/api/torob/products',
  path: '/api/torob/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentZibalCallbackRoute = ApiPaymentZibalCallbackRouteImport.update({
  id: '/api/payment/zibal/callback',
  path: '/api/payment/zibal/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicModelSplatRoute = ApiPublicModelSplatRouteImport.update({
  id: '/api/public/model/$',
  path: '/api/public/model/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorobV1OrdersRoute = ApiTorobV1OrdersRouteImport.update({
  id: '/api/torob/v1/orders',
  path: '/api/torob/v1/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorobWebhooksProcessRoute = ApiTorobWebhooksProcessRouteImport.update({
  id: '/api/torob/webhooks/process',
  path: '/api/torob/webhooks/process',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/product-sitemap.xml': typeof ProductSitemapDotxmlRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/discounts': typeof AuthenticatedAdminDiscountsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/torob': typeof AuthenticatedAdminTorobRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/torob/health': typeof ApiTorobHealthRoute
  '/api/torob/products': typeof ApiTorobProductsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/api/payment/zibal/callback': typeof ApiPaymentZibalCallbackRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/model/$': typeof ApiPublicModelSplatRoute
  '/api/torob/v1/orders': typeof ApiTorobV1OrdersRoute
  '/api/torob/webhooks/process': typeof ApiTorobWebhooksProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/product-sitemap.xml': typeof ProductSitemapDotxmlRoute
  '/search': typeof SearchRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/discounts': typeof AuthenticatedAdminDiscountsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/torob': typeof AuthenticatedAdminTorobRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/torob/health': typeof ApiTorobHealthRoute
  '/api/torob/products': typeof ApiTorobProductsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/api/payment/zibal/callback': typeof ApiPaymentZibalCallbackRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/model/$': typeof ApiPublicModelSplatRoute
  '/api/torob/v1/orders': typeof ApiTorobV1OrdersRoute
  '/api/torob/webhooks/process': typeof ApiTorobWebhooksProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/product-sitemap.xml': typeof ProductSitemapDotxmlRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/discounts': typeof AuthenticatedAdminDiscountsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/torob': typeof AuthenticatedAdminTorobRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/torob/health': typeof ApiTorobHealthRoute
  '/api/torob/products': typeof ApiTorobProductsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/api/payment/zibal/callback': typeof ApiPaymentZibalCallbackRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/model/$': typeof ApiPublicModelSplatRoute
  '/api/torob/v1/orders': typeof ApiTorobV1OrdersRoute
  '/api/torob/webhooks/process': typeof ApiTorobWebhooksProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/product-sitemap.xml'
    | '/search'
    | '/admin'
    | '/profile'
    | '/payment/callback'
    | '/products/$slug'
    | '/products/'
    | '/admin/categories'
    | '/admin/discounts'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/torob'
    | '/admin/users'
    | '/orders/$id'
    | '/api/public/health'
    | '/api/torob/health'
    | '/api/torob/products'
    | '/admin/'
    | '/orders/'
    | '/api/payment/zibal/callback'
    | '/api/public/img/$'
    | '/api/public/model/$'
    | '/api/torob/v1/orders'
    | '/api/torob/webhooks/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/product-sitemap.xml'
    | '/search'
    | '/profile'
    | '/payment/callback'
    | '/products/$slug'
    | '/products'
    | '/admin/categories'
    | '/admin/discounts'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/torob'
    | '/admin/users'
    | '/orders/$id'
    | '/api/public/health'
    | '/api/torob/health'
    | '/api/torob/products'
    | '/admin'
    | '/orders'
    | '/api/payment/zibal/callback'
    | '/api/public/img/$'
    | '/api/public/model/$'
    | '/api/torob/v1/orders'
    | '/api/torob/webhooks/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/product-sitemap.xml'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/payment/callback'
    | '/products/$slug'
    | '/products/'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/discounts'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/torob'
    | '/_authenticated/admin/users'
    | '/_authenticated/orders/$id'
    | '/api/public/health'
    | '/api/torob/health'
    | '/api/torob/products'
    | '/_authenticated/admin/'
    | '/_authenticated/orders/'
    | '/api/payment/zibal/callback'
    | '/api/public/img/$'
    | '/api/public/model/$'
    | '/api/torob/v1/orders'
    | '/api/torob/webhooks/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ProductSitemapDotxmlRoute: typeof ProductSitemapDotxmlRoute
  SearchRoute: typeof SearchRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiTorobHealthRoute: typeof ApiTorobHealthRoute
  ApiTorobProductsRoute: typeof ApiTorobProductsRoute
  ApiPaymentZibalCallbackRoute: typeof ApiPaymentZibalCallbackRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
  ApiPublicModelSplatRoute: typeof ApiPublicModelSplatRoute
  ApiTorobV1OrdersRoute: typeof ApiTorobV1OrdersRoute
  ApiTorobWebhooksProcessRoute: typeof ApiTorobWebhooksProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-sitemap.xml': {
      id: '/product-sitemap.xml'
      path: '/product-sitemap.xml'
      fullPath: '/product-sitemap.xml'
      preLoaderRoute: typeof ProductSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/discounts': {
      id: '/_authenticated/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AuthenticatedAdminDiscountsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/torob': {
      id: '/_authenticated/admin/torob'
      path: '/torob'
      fullPath: '/admin/torob'
      preLoaderRoute: typeof AuthenticatedAdminTorobRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torob/health': {
      id: '/api/torob/health'
      path: '/api/torob/health'
      fullPath: '/api/torob/health'
      preLoaderRoute: typeof ApiTorobHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torob/products': {
      id: '/api/torob/products'
      path: '/api/torob/products'
      fullPath: '/api/torob/products'
      preLoaderRoute: typeof ApiTorobProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/zibal/callback': {
      id: '/api/payment/zibal/callback'
      path: '/api/payment/zibal/callback'
      fullPath: '/api/payment/zibal/callback'
      preLoaderRoute: typeof ApiPaymentZibalCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/model/$': {
      id: '/api/public/model/$'
      path: '/api/public/model/$'
      fullPath: '/api/public/model/$'
      preLoaderRoute: typeof ApiPublicModelSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torob/v1/orders': {
      id: '/api/torob/v1/orders'
      path: '/api/torob/v1/orders'
      fullPath: '/api/torob/v1/orders'
      preLoaderRoute: typeof ApiTorobV1OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torob/webhooks/process': {
      id: '/api/torob/webhooks/process'
      path: '/api/torob/webhooks/process'
      fullPath: '/api/torob/webhooks/process'
      preLoaderRoute: typeof ApiTorobWebhooksProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminDiscountsRoute: typeof AuthenticatedAdminDiscountsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTorobRoute: typeof AuthenticatedAdminTorobRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminDiscountsRoute: AuthenticatedAdminDiscountsRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
    AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTorobRoute: AuthenticatedAdminTorobRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ProductSitemapDotxmlRoute: ProductSitemapDotxmlRoute,
  SearchRoute: SearchRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiTorobHealthRoute: ApiTorobHealthRoute,
  ApiTorobProductsRoute: ApiTorobProductsRoute,
  ApiPaymentZibalCallbackRoute: ApiPaymentZibalCallbackRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
  ApiPublicModelSplatRoute: ApiPublicModelSplatRoute,
  ApiTorobV1OrdersRoute: ApiTorobV1OrdersRoute,
  ApiTorobWebhooksProcessRoute: ApiTorobWebhooksProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
